Below we will try and fit a Logisitc Regression Model step by step for the XOR problem.
Fill in the code where there is a `_FILL_` specified. For this model, we have $x_1$ and $x_2$ are either 0/1 each and $y = x_1 + x_2 - 2x_1x_2$. Notice that this is True (1) if $x_1 = 1$ and $x_2 = 0$ OR $x_1 = 0$ and $x_2 = 1$; $y$ is zero otherwise.

In [ ]:
import torch.nn as nn
import torch
# Don't fill this in
_FILL_ = '_FILL_'

In [ ]:
x_data = [[0, 0], [0, 1], [1, 0], [1, 1]]
y_data = [[0], [1], [1], [0]]
x_data = torch.Tensor(x_data)
y_data = torch.Tensor(y_data)

In [ ]:
# Define each tensor to be 1x1 and have them require a gradient for tracking; these are parameters
alpha = _FILL_
beta_1 = _FILL_
beta_2 = _FILL_

In [ ]:
lr = 0.01

for epoch in range(10):
  for x, y in zip(x_data, y_data):

    # Have z be beta_2*x[0] + beta_1*x[1] + alpha
    z = _FILL_

    # Push z through a nn.Sigmoid layer to get the p(y=1)
    a = _FILL_

    # Write the loss manually between y and a
    loss = _FILL_

    # Get the loss gradients; the gradients with respect to alpha, beta_1, beta_2
    _FILL_

    # Manually update the gradients
    # What we do below is wrapped within this clause because weights have required_grad=True but we don't need to track this in autograd
    with torch.no_grad():
        # Do an update for each parameter
        _FILL_
        _FILL_
        _FILL_

        # Manually zero the gradients after updating weights
        _FILL_
        _FILL_
        _FILL_

  # Manually get the accuracy of the model after each epoch
  with torch.no_grad():
    print(f'Epoch: {epoch}')
    y_pred = []
    loss = 0.0

    for x, y in zip(x_data, y_data):
      # Get z
      z = _FILL_

      # Get a
      a = _FILL_

      # Get the loss
      loss += _FILL_

      # Get the prediction given a
      _FILL_

    # Get the current accuracy over 4 points; make this a tensor
    y_pred = _FILL_

    accuracy = _FILL_
    loss = loss / 4

    # Print the accuracy and the loss
    # You want the item in the tensor thats 1x1
    print('Loss: {} Accuracy: {}'.format(_FILL_, _FILL_))

Epoch: 0
Loss: 0.7430764436721802 Accuracy: 0.5
Epoch: 1
Loss: 0.7417216300964355 Accuracy: 0.5
Epoch: 2
Loss: 0.7404038906097412 Accuracy: 0.5
Epoch: 3
Loss: 0.7391220331192017 Accuracy: 0.5
Epoch: 4
Loss: 0.7378755211830139 Accuracy: 0.5
Epoch: 5
Loss: 0.736663281917572 Accuracy: 0.5
Epoch: 6
Loss: 0.7354844808578491 Accuracy: 0.5
Epoch: 7
Loss: 0.7343384027481079 Accuracy: 0.5
Epoch: 8
Loss: 0.7332241535186768 Accuracy: 0.5
Epoch: 9
Loss: 0.7321408987045288 Accuracy: 0.5


Exercise 1: Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis.



In [ ]:
_FILL_

tensor([[[0.0977, 0.6405, 0.2197],
         [0.0076, 0.6612, 0.6541]]])

Exercise 2: Remove the extra dimension you just added to the previous tensor.



In [ ]:
_FILL_

tensor([[0.0977, 0.6405, 0.2197],
        [0.0076, 0.6612, 0.6541]])

Exercise 3: Create a random tensor of shape 5x3 in the interval [3, 7)



In [ ]:
_FILL_

tensor([[4.4375, 4.0747, 3.0686],
        [6.2739, 4.4818, 4.2337],
        [5.4632, 4.4997, 4.3507],
        [6.2013, 6.9733, 4.5900],
        [4.2644, 3.3225, 5.2225]])

Exercise 4: Create a tensor with values from a normal distribution (mean=0, std=1).



In [ ]:
_FILL_

exercise 5: Retrieve the indexes of all the non zero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).



In [ ]:
_FILL_

tensor([[0],
        [1],
        [2],
        [4]])

Exercise 6: Create a random tensor of size (3,1) and then horizonally stack 4 copies together.



In [ ]:
_FILL_

tensor([[0.1503, 0.1503, 0.1503, 0.1503],
        [0.7086, 0.7086, 0.7086, 0.7086],
        [0.3414, 0.3414, 0.3414, 0.3414]])

Exercise 7: Return the batch matrix-matrix product of two 3 dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).



In [ ]:
_FILL_

tensor([[[1.6394, 0.6833, 1.5837, 1.5976],
         [1.1472, 0.3890, 1.0009, 1.2655],
         [1.0815, 0.5244, 1.0628, 1.4311],
         [1.9040, 1.2040, 1.4985, 1.4086]],

        [[0.9391, 1.2059, 1.3412, 0.8154],
         [1.3120, 1.4383, 1.8123, 1.1125],
         [0.5450, 1.4864, 1.3260, 0.6719],
         [0.6573, 1.7938, 1.7714, 1.0374]],

        [[0.9832, 0.5582, 1.1056, 1.0532],
         [1.9757, 1.1756, 2.0718, 1.7928],
         [1.2413, 0.8302, 1.0994, 0.5718],
         [1.7323, 0.9673, 1.6841, 1.2645]]])

Exercise 8: Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).



In [ ]:
_FILL_

tensor([[[0.3375, 0.2907, 0.3181, 0.1812],
         [1.1075, 1.0032, 1.0962, 1.0600],
         [1.4107, 1.2923, 1.7551, 1.4518],
         [1.1264, 0.7016, 1.4619, 0.9141]],

        [[1.1713, 0.7899, 1.4845, 0.5677],
         [1.5807, 1.1571, 1.4543, 1.1874],
         [1.3340, 0.9715, 1.3254, 0.9939],
         [1.3030, 0.6757, 1.9461, 1.0246]],

        [[0.9775, 0.8165, 1.1316, 0.9601],
         [0.9570, 0.9399, 0.8771, 0.8693],
         [0.9590, 0.6913, 0.9538, 0.7193],
         [1.1810, 0.8096, 1.4295, 1.1040]]])

Exercise 9: Create a 1x1 random tensor and get the value inside of this tensor as a scalar. No tensor.

In [ ]:
_FILL_

0.31901270151138306

Exercise 10: Create a 2x1 tensor and have it require a gradient. Have $x$, this tensor, hold [-2, 1]. Set $y=x_1^2 + x_2^2$ and get the gradient of y wirht respect to $x_1$ and then $x_2$.

In [ ]:
_FILL_

tensor([[0.7460],
        [0.3626]])

Exercise 11: Check if cuda is available (it shuld be if in the Runtime setting for colab you choose the GPU). If it is, move $x$ above to a CUDA device. Create a new tensor of the same shape as $x$ and put it on the cpu. Try and add these tensors. What happens. How do you fix this?

In [ ]:
_FILL_

RuntimeError: ignored