Below we will try and fit a Logisitc Regression Model step by step for the XOR problem.
Fill in the code where there is a `_FILL_` specified. For this model, we have $x_1$ and $x_2$ are either 0/1 each and $y = x_1 + x_2 - 2x_1x_2$. Notice that this is True (1) if $x_1 = 1$ and $x_2 = 0$ OR $x_1 = 0$ and $x_2 = 1$; $y$ is zero otherwise.

In [80]:
import torch.nn as nn
import torch
# Don't fill this in
_FILL_ = '_FILL_'

In [81]:
x_data = [[0, 0], [0, 1], [1, 0], [1, 1]]
y_data = [[0], [1], [1], [0]]
x_data = torch.Tensor(x_data)
y_data = torch.Tensor(y_data)

In [82]:
# Define each tensor to be 1x1 and have them require a gradient for tracking; these are parameters
alpha = torch.rand([1, 1], requires_grad=True)
beta_1 = torch.rand([1, 1], requires_grad=True)
beta_2 = torch.rand([1, 1], requires_grad=True)

In [85]:
lr = 0.01

sigmoid = nn.Sigmoid()
for epoch in range(100):
  for x, y in zip(x_data, y_data):

    # Have z be beta_2*x[0] + beta_1*x[1] + alpha
    z = beta_2*x[0] + beta_1*x[1] + alpha

    # Push z through a nn.Sigmoid layer to get the p(y=1)
    a = sigmoid(z)

    # Write the loss manually between y and a
    loss = -(y * torch.log(a) + (1 - y) * torch.log(1-a))
    # Get the loss gradients; the gradients with respect to alpha, beta_1, beta_2
    loss.backward()

    # Manually update the gradients
    # What we do below is wrapped within this clause because weights have required_grad=True but we don't need to track this in autograd
    with torch.no_grad():
        # Do an update for each parameter
        alpha -= lr * alpha.grad
        beta_1 -= lr * beta_1.grad
        beta_2 -= lr * beta_2.grad

        # Manually zero the gradients after updating weights
        alpha.grad.zero_()
        beta_1.grad.zero_()
        beta_2.grad.zero_()

  # Manually get the accuracy of the model after each epoch
  with torch.no_grad():
    print(f'Epoch: {epoch}')
    y_pred = []
    loss = 0.0

    for x, y in zip(x_data, y_data):
      # Get z
      z = beta_2*x[0] + beta_1*x[1] + alpha

      # Get a
      a = sigmoid(z)

      # Get the loss
      loss += -(y * torch.log(a) + (1 - y) * torch.log(1-a))

      # Get the prediction given a
      y_pred.append(a > 0.5)

    # Get the current accuracy over 4 points; make this a tensor
    y_pred = torch.Tensor(y_pred)

    accuracy = (y_data.view(-1) == y_pred).sum() / 4
    loss = loss / 4

    # Print the accuracy and the loss
    # You want the item in the tensor thats 1x1
    print(f"Loss: {loss.item():.10f} Accuracy: {accuracy}")

Epoch: 0
Loss: 0.6994901896 Accuracy: 0.5
Epoch: 1
Loss: 0.6993739605 Accuracy: 0.5
Epoch: 2
Loss: 0.6992611885 Accuracy: 0.5
Epoch: 3
Loss: 0.6991516352 Accuracy: 0.5
Epoch: 4
Loss: 0.6990453005 Accuracy: 0.5
Epoch: 5
Loss: 0.6989420652 Accuracy: 0.5
Epoch: 6
Loss: 0.6988418102 Accuracy: 0.5
Epoch: 7
Loss: 0.6987444162 Accuracy: 0.5
Epoch: 8
Loss: 0.6986498833 Accuracy: 0.5
Epoch: 9
Loss: 0.6985580921 Accuracy: 0.5
Epoch: 10
Loss: 0.6984688640 Accuracy: 0.5
Epoch: 11
Loss: 0.6983822584 Accuracy: 0.5
Epoch: 12
Loss: 0.6982981563 Accuracy: 0.5
Epoch: 13
Loss: 0.6982164383 Accuracy: 0.5
Epoch: 14
Loss: 0.6981370449 Accuracy: 0.5
Epoch: 15
Loss: 0.6980599165 Accuracy: 0.5
Epoch: 16
Loss: 0.6979848146 Accuracy: 0.5
Epoch: 17
Loss: 0.6979120970 Accuracy: 0.5
Epoch: 18
Loss: 0.6978413463 Accuracy: 0.75
Epoch: 19
Loss: 0.6977725029 Accuracy: 0.75
Epoch: 20
Loss: 0.6977056265 Accuracy: 0.75
Epoch: 21
Loss: 0.6976407170 Accuracy: 0.75
Epoch: 22
Loss: 0.6975774765 Accuracy: 0.75
Epoch: 23
Loss: 

Exercise 1: Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis.



In [55]:
x = torch.Tensor([2, 2])
x = x.unsqueeze(0)

Exercise 2: Remove the extra dimension you just added to the previous tensor.



In [56]:
x = x.squeeze(0)

Exercise 3: Create a random tensor of shape 5x3 in the interval [3, 7)



In [57]:
x = 3 + 4 * torch.rand(5, 3)

Exercise 4: Create a tensor with values from a normal distribution (mean=0, std=1).



In [58]:
x = torch.randn(5, 3)

exercise 5: Retrieve the indexes of all the non zero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).



In [59]:
result = torch.nonzero(torch.Tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

Exercise 6: Create a random tensor of size (3,1) and then horizonally stack 4 copies together.



In [60]:
x = torch.rand(3, 1)
y = x.repeat(1, 4)
x, y

(tensor([[0.9250],
         [0.0397],
         [0.1040]]),
 tensor([[0.9250, 0.9250, 0.9250, 0.9250],
         [0.0397, 0.0397, 0.0397, 0.0397],
         [0.1040, 0.1040, 0.1040, 0.1040]]))

Exercise 7: Return the batch matrix-matrix product of two 3 dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).



In [61]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
c = torch.bmm(a, b)
a, b, c

(tensor([[[0.6348, 0.2725, 0.2501, 0.4860, 0.2934],
          [0.9260, 0.2047, 0.8937, 0.4566, 0.2098],
          [0.7305, 0.7653, 0.3733, 0.6413, 0.0547],
          [0.1454, 0.6189, 0.6580, 0.3643, 0.1724]],
 
         [[0.6883, 0.2452, 0.8855, 0.9905, 0.8135],
          [0.6893, 0.6772, 0.2069, 0.4175, 0.1831],
          [0.6751, 0.1996, 0.2804, 0.0087, 0.5793],
          [0.2693, 0.7480, 0.3078, 0.4336, 0.7088]],
 
         [[0.8103, 0.3029, 0.4939, 0.0853, 0.0329],
          [0.8171, 0.0466, 0.9702, 0.8670, 0.5576],
          [0.7162, 0.1998, 0.2009, 0.9989, 0.1979],
          [0.8298, 0.6766, 0.1627, 0.7537, 0.3901]]]),
 tensor([[[0.1222, 0.1961, 0.7390, 0.7704],
          [0.6497, 0.6177, 0.5646, 0.4525],
          [0.6548, 0.4661, 0.6659, 0.6355],
          [0.7970, 0.3389, 0.1691, 0.3490],
          [0.8177, 0.3725, 0.1289, 0.9859]],
 
         [[0.4424, 0.0505, 0.2097, 0.4959],
          [0.3744, 0.9181, 0.2167, 0.7170],
          [0.8459, 0.5364, 0.2008, 0.8231],
          [0

Exercise 8: Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).



In [62]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
c = torch.matmul(a, b)
a, b, c

Exercise 9: Create a 1x1 random tensor and get the value inside of this tensor as a scalar. No tensor.

In [65]:
x = torch.rand(1, 1)
s = x.item()
type(s), x, s

(float, tensor([[0.8244]]), 0.8243800401687622)

Exercise 10: Create a 2x1 tensor and have it require a gradient. Have $x$, this tensor, hold [-2, 1]. Set $y=x_1^2 + x_2^2$ and get the gradient of y wirht respect to $x_1$ and then $x_2$.

In [68]:
x = torch.tensor([[-2.0], [1.0]], requires_grad=True)
y = x[0, 0] ** 2 + x[1, 0] ** 2
y.backward()
x.grad


tensor([[-4.],
        [ 2.]])

Exercise 11: Check if cuda is available (it shuld be if in the Runtime setting for colab you choose the GPU). If it is, move $x$ above to a CUDA device. Create a new tensor of the same shape as $x$ and put it on the cpu. Try and add these tensors. What happens. How do you fix this?

In [79]:
torch.cuda.is_available()
x = torch.rand(2,2)
y = torch.rand_like(x)
x = x.to("cuda")
try:
    z = x + y
except Exception as e:
    print(e)

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Move y above to a CUDA device too.